create database customer_behavior
select * from customer
-- Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(AVG(review_rating),2) as rating
from customer
group by item_purchased
order by rating desc
limit 5

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,
ROUND(AVG(purchase_amount), 2)
from customer
where shipping_type in ('Standard','Express' )
group by shipping_type

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customers,
ROUND(AVG(purchase_amount), 2) as avg_spend,
ROUND(SUM(purchase_amount), 2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases 
-- with discounts applied?
select item_purchased,
ROUND((sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*)) * 100, 2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
select customer_type, count(*) from 
(select
(case when previous_purchases = 0 then 'New' else( case when previous_purchases <= 5 then 'Returning' else 'Loyal' end) end) as customer_type
from customer) sq
group by customer_type


select
case
	when previous_purchases = 0 then 'New'
    when previous_purchases <=5 then 'Returning'
    else 'Loyal' end as customer_type,
count(*)
from customer
group by customer_type


with customer_type as (
select customer_id, previous_purchases,
 case
	when previous_purchases = 0 then 'New'
    when previous_purchases <= 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
    
    from customer
)

select customer_segment, count(*)
from customer_type
group by customer_segment

-- Q8. What are the top 3 most purchased products within each category?
select rn ,category, item_purchased, total_purchases
from
(
	select category, item_purchased, count(*) as total_purchases,
    row_number() over(partition by category
    order by count(*) desc ) as rn
    
    from customer
    group by category, item_purchased
) ranked_products

where rn <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

-- Q10. What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;


